import base64
import os
import subprocess
import ollama

def enforce_audio_format(input_path, output_path="processed_input.wav"):
    """
    Force-converts audio using ffmpeg to 16kHz, mono, 16-bit PCM WAV.
    This structure injects the strict RIFF/WAVE header headers needed by Ollama.
    """
    print(f"Resampling audio asset via FFmpeg: {input_path} -> {output_path}")
    command = [
        "ffmpeg", "-y", "-i", input_path,
        "-acodec", "pcm_s16le",
        "-ar", "16000",
        "-ac", "1",
        output_path
    ]
    # Run conversion silently
    subprocess.run(command, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=True)
    return output_path

def transcribe_and_translate_audio_stream(audio_file_path):
    """
    Encodes optimized 16kHz WAV to base64 and streams response from Gemma 4 E2B.
    """
    if not os.path.exists(audio_file_path):
        raise FileNotFoundError(f"Audio file not found at: {audio_file_path}")
    
    # 1. Enforce strict 16kHz mono layout required by the local model parser
    processed_audio = enforce_audio_format(audio_file_path)
        
    print(f"Reading target media payload: {processed_audio}")
    with open(processed_audio, "rb") as f:
        audio_bytes = f.read()
    
    # Encode audio file into base64 format
    audio_b64 = base64.b64encode(audio_bytes).decode('utf-8')
    
    # Prompt targeting Indian language translation tasks
    system_prompt = (
        "Listen to this audio payload. Transcribe the spoken speech exactly into "
        "its native Indian script (or code-mixed text), then provide its direct "
        "Hindi translation right underneath."
    )
    
    print("Streaming payload to local unquantized Gemma 4 E2B engine...")
    print("\n================ SYSTEM INFERENCE RESPONSE ================")
    
    # Ollama identifies audio arrays implicitly inside the images parameter array 
    # when the payload contains valid WAV RIFF magic bytes.
    response_stream = ollama.chat(
        model='gemma4:e2b',
        messages=[{
            'role': 'user',
            'content': system_prompt,
            'images': [audio_b64]  
        }],
        stream=True        
    )
    
    # Iterate through the chunks as they are generated by the CPU
    for chunk in response_stream:
        print(chunk['message']['content'], end='', flush=True)
        
    print("\n==========================================================")
    
    # Clean up temporary resampled asset
    if os.path.exists("processed_input.wav"):
        os.remove("processed_input.wav")

if __name__ == "__main__":
    TARGET_FILE = "audio.wav"
    
    # Generate an actual sound wave pattern instead of a flat silence line if testing
    if not os.path.exists(TARGET_FILE):
        print(f"Generating synthetic frequency asset '{TARGET_FILE}' for pipeline testing...")
        os.system(f"ffmpeg -f lavfi -i sine=frequency=440:duration=3 -ac 1 -ar 16000 {TARGET_FILE} -y")
        
    transcribe_and_translate_audio_stream(TARGET_FILE)
